[package]
name = "DuckSlayer"
version = "0.1.0"
edition = "2021"

[dependencies]
# Using the github because bevy_ui doesn't compile with track_location with the cargo version of bevy. Inane, yes.
bevy = "0.16.1"
bevy_egui = "0.34.1"
strum = "0.27"
strum_macros = "0.27"
